# Generated by Django 2.2.8 on 2020-10-28 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201001_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminuserinfo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='adminuserinfo',
            name='password',
        ),
    ]
